#!/bin/sh

DOCKER_IMAGE=ubuntu_x11

docker build -t $DOCKER_IMAGE - << __EOF__
    FROM ubuntu

    RUN apt-get update

    ENV DEBIAN_FRONTEND noninteractive

    RUN apt-get install -y \
        x11-apps \
        tmux \
        zsh \
        hollywood \
        firefox

    RUN useradd -ms /bin/zsh user

    ENV DISPLAY :0

    CMD /usr/bin/tmux
__EOF__

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth

xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

docker run --rm -ti -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH $DOCKER_IMAGE
