#!/bin/sh

interval=1
info="/sys/class/net/"

prefix="/sys/class/net"
for interface in "$prefix/wifi*"; do
    rx1=$(cat $interface/statistics/rx_bytes)
    tx1=$(cat $interface/statistics/tx_bytes)

    $(sleep $((interval))s)

    rx2=$(cat $interface/statistics/rx_bytes)
    tx2=$(cat $interface/statistics/tx_bytes)

    down=`awk -v rx2="$rx2" -v rx1="$rx1" -v interval="$interval" 'BEGIN{printf("%.2f\n"), (rx2-rx1)/(interval*1024*1000)}';`
    up=`awk -v tx2="$tx2" -v tx1="$tx1" -v interval="$interval" 'BEGIN{printf("%.2f\n"), (tx2-tx1)/(interval*1024*1000)}';`

    echo " $down MB/s    $up MB/s"
done
