#!/bin/sh

delim=" | "

status() {
    check-gpg-cached && echo "$delim"
    check-syncing-documents && echo "$delim"
    # check-updates-packages && echo "$delim"
    check-mail-unread && echo "$delim"
    # cpu
    # mem
    check-interface-speed && echo "$delim"
    check-cpu-temperature && echo "$delim"
    # volume
    check-battery && echo "$delim"
    check-datetime && echo " "
    echo $time
}

while true; do
	xsetroot -name "$(status | tr '\n' ' ')" &
    sleep 3
done
