#!/bin/sh

while read file
do
    case "$1" in
        "d")
            mv "$file" ~/.local/share/Trash/ && notify-send -i "$PWD/$file" "Trashed" "$file moved to trash." ;;
        "D")
            [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send -i "$PWD/$file" "Deleted" "$file deleted." ;;
        "C-c")
            echo -n "$file" | xclip -selection clipboard && notify-send -i "$PWD/$file" "Copied" "$file copied to clipboard" & ;;
        "y")
            echo -n "$file" | xclip -selection clipboard && notify-send -i "$PWD/$file" "Copied" "$file copied to clipboard" & ;;
        "Y")
            echo -n "$(readlink -f "$file")" | xclip -selection clipboard && notify-send -i "$PWD/$file" "Copied" "$(readlink -f "$file") copied to clipboard" & ;;
        "c")
            [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.bmdirs | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
            [ -z "$destdir" ] && exit
            cp "$file" "$destdir" && notify-send -i "$PWD/$file" "Copied" -i "$(readlink -f "$file")" "$file copied to $destdir." & ;;
        "m")
            [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.bmdirs | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
            [ -z "$destdir" ] && exit
            mv "$file" "$destdir" && notify-send -i "$PWD/$file" "Moved" -i "$(readlink -f "$file")" "$file moved to $destdir." & ;;
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "R")
            convert -rotate -90 "$file" "$file" ;;
        "f")
            convert -flop "$file" "$file" ;;
        "w")
            feh --bg-center "$file";;
        "b")
            feh --bg-fill "$file";;
        "G")
            gimp "$file" & ;;
        "C-x")
                lf -remote "send select '$file'"
                lf -remote "send toggle"
            ;;
    esac
done
