#!/bin/sh

# tapping
xinput --set-prop "Synaptics TM3418-002" --type=int --format=8 "libinput Tapping Enabled" "1"

# faster mouse speed
xinput --set-prop "Synaptics TM3418-002" --type=float --format=32 "libinput Accel Speed" ".5"

# scrolling both ways
xinput --set-prop "Synaptics TM3418-002" --type=int --format=8 "Synaptics Two-Finger Scrolling" 1, 1 &

# natural scrolling
xinput --set-prop "Synaptics TM3418-002" --type=int --format=8 "libinput Natural Scrolling Enabled" 1
