#!/bin/sh

projects="
    /home/lander/Documents/Work/WeGroup/Car/AutoGids\n
    /home/lander/Documents/Work/WeGroup/wg-be-api-address\n
    /home/lander/Documents/Work/WeGroup/wg-be-api-house-property
"

project=$(echo $projects | dmenu -i) || exit

cd $project

i3-msg split v
$TERMINAL -e zsh -c "pipenv run nvim" &
sleep .2

$TERMINAL -e zsh -c "pipenv run python run.py" &
sleep .2

i3-msg split h
$TERMINAL -e zsh -c "pipenv shell" &
