###########################################################################
#                             Docker Snippets                             #
###########################################################################

snippet esleep "Entrypoint sleep"
ENTRYPOINT [ "sleep", "9999999999" ]
endsnippet

# vim: ft=snippets
