#!/bin/sh

ssh -Y dekra-rdp-passtrough "./connect-dekra"

# xfreerdp \
#     /u:$DEKRA_USER \
#     /p:$DEKRA_PASS \
#     /d:$DEKRA_DOMAIN \
#     /v:$DEKRA_SERVER \
#     /sound \
#     /dynamic-resolution \
#     /drive:home,/home/lander/Documents/Work/WeGroup/Claims/Dekra/Share
#     # +auto-reconnect \
#     # +drives \
#     # +fonts \
#     # -themes \
#     # -wallpaper
