general {
    hide_cursor = true
    ignore_empty_input = true
}

auth {
    pam {
        enabled = true
        module = hyprlock
    }
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250
    }
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8917
    brightness = 0.8172
    vibrancy = 0.1686
    vibrancy_darkness = 0.05
}

input-field {
    monitor =
    size = 300, 55
    position = 0, -120
    halign = center
    valign = center

    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.4
    dots_center = true
    dots_rounding = -1

    rounding = 12
    outer_color = rgba(b4befe40)
    inner_color = rgba(1e1e2eaa)
    font_color = rgb(cdd6f4)
    check_color = rgb(b4befe)
    fail_color = rgb(f38ba8)
    fail_text = <i>$FAIL</i>
    placeholder_text =

    fade_on_empty = false
    swap_font_color = false
    hide_input = false

    capslock_color = rgb(f9e2af)
    invert_numlock = false
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(cdd6f4)
    font_size = 70
    font_family = Noto Sans
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color = rgb(cdd6f4)
    font_size = 18
    font_family = Noto Sans
    position = 0, 0
    halign = center
    valign = center
}
