#!/bin/sh

ext=${1##*.}
out=${2:-/tmp}
extensions="doc docx odt ppt pptx xls xlsx"

if [ -z "$1" ]; then
    echo "- Options: .doc, .docx, .odt .xls .xlsx"
    exit
fi

if ! echo $extensions | grep -w $ext >/dev/null; then
    echo "Provide a valid document"
    echo "- Options: $extensions"
    exit
fi

/usr/bin/libreoffice --headless --convert-to pdf --outdir $out "$1"
