#!/bin/sh

config_files=$(find $HOME/.scripts $HOME/dotfiles $HOME/Git/mutt -type f -not -path "*/.git/*" -not -path "*/.oh-my-zsh/*" | sort | uniq)

file=$(echo "$config_files" | dmenu -i) || exit

cd $(dirname "$file")

$TERMINAL -e $EDITOR $file
