#!/bin/sh

if pgrep trayer ; then
    killall trayer
else
    setsid trayer \
    --edge bottom \
    --align right \
    --distance 4 \
    --distancefrom right \
    --widthtype request \
    --heighttype request \
    --transparent true \
    --alpha 200 \
    &
fi
