#!/bin/sh

if [ "$1" = "" ]; then

    echo "specify a SSID"
    return

fi

sudo grep ssid=\"$1\" /etc/wpa_supplicant/wpa_supplicant.conf > /dev/null && echo "SSID already saved" && return

wpa_passphrase "$1" | sudo tee -a /etc/wpa_supplicant/wpa_supplicant.conf

sudo systemctl restart dhcpcd.service
