#!/bin/sh

check_unread () {
    # unread=$(find ~/.mail/*/INBOX/new | grep new/ | wc | awk '{print $1;}')
    unread=$(find ~/.mail/*/INBOX/new | grep new/ | wc -l)

    if [ "$unread" != "0" ]; then
        echo $unread
    else
        echo ""
    fi
}

check_unread
