#!/bin/sh

check_unread () {
    # unread=$(find ~/.mail/*/INBOX/new | grep new/ | wc | awk '{print $1;}')
    if [ $1 ]; then
        unread=$(find ~/.mail/$1/INBOX/new | grep new/ | wc -l)
    else
        unread=$(find ~/.mail/*/INBOX/new | grep new/ | wc -l)
    fi

    if [ "$unread" != "0" ]; then
        echo $unread
    else
        echo ""
    fi
}

check_unread $1
