#!/bin/sh

SUBFOLDER=${1:-"*"}

# unread=$(find ~/.mail/*/INBOX/new | grep new/ | wc | awk '{print $1;}')
unread=$(find ~/.mail/$SUBFOLDER/INBOX/new | grep new/ | wc -l)

if [ "$unread" != "0" ]; then
    echo "  $unread"
else
    exit 1
fi
