#!/usr/bin/sh

killall -q polybar

# wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

for m in $(polybar --list-monitors | tac | cut -d":" -f1); do
    MONITOR=$m polybar --reload bar &
done
echo "Bars launched"
